### PR TITLE
Allow ignition on local usage.

### LINKED ISSUE #81: Cannot run solution in this environment
This is just happening after the last update:

# note: this is in the production environment.

```
{
    "class": "Spatie\\LaravelIgnition\\Exceptions\\CannotExecuteSolutionForNonLocalEnvironment",
    "message": "Cannot run solution in this environment",
    "code": 0,
    "file": "/var/www/vendor/spatie/laravel-ignition/src/Exceptions/CannotExecuteSolutionForNonLocalEnvironment.php:14",
    "trace": [
        "/var/www/vendor/spatie/laravel-ignition/src/Http/Controllers/ExecuteSolutionController.php:33",
        "/var/www/vendor/spatie/laravel-ignition/src/Http/Controllers/ExecuteSolutionController.php:20",
        "/var/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:48",
        "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php:261",
        "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php:204",
        "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php:725",
        "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:141",
        "/var/www/vendor/spatie/laravel-ignition/src/Http/Middleware/RunnableSolutionsEnabled.php:15",
        "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:180",
        "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:116",
        "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php:727",
        "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php:702",
        "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php:666",
        "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php:655",
        "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:167",
        "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:141",
        "/var/www/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Http/SetRequestIpMiddleware.php:45",
        "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:180",
        "/var/www/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Http
```

composer.json:
```
{
  "name": "laravel/laravel",
  "type": "project",
  "description": "The Laravel Framework.",
  "keywords": [
	"framework",
	"laravel"
  ],
  "license": "MIT",
  "require": {
    "php": "^8.1",
    "ext-curl": "*",
    "ext-json": "*",
    "ext-openssl": "*",
    "ext-pdo": "*",
    "aws/aws-sdk-php-laravel": "~3.0",
    "darkaonline/l5-swagger": "^8.0",
    "doctrine/dbal": "^3.1",
    "fruitcake/laravel-cors": "^3.0",
    "gamegos/jws": "^1.0",
    "goetas-webservices/xsd-reader": "^0.3.6",
    "guzzlehttp/guzzle": "^7.0.1",
    "intervention/image": "^2.5",
    "laravel/framework": "^9.0",
    "laravel/octane": "^1.2",
    "laravel/telescope": "^4.7",
    "laravel/tinker": "^2.5",
    "league/flysystem-aws-s3-v3": "^3.0",
    "maatwebsite/excel": "^3.1",
    "monarobase/country-list": "^3.2",
    "namshi/jose": "^7.2",
    "owen-it/laravel-auditing": "^13.0",
    "php-open-source-saver/jwt-auth": "^1.1",
    "phpseclib/phpseclib": "^3.0",
    "predis/predis": "^1.1",
    "pusher/pusher-php-server": "^7.0",
    "s-ichikawa/laravel-sendgrid-driver": "^4.0",
    "scotteh/php-goose": "^1.1",
    "sentry/sentry-laravel": "^2.11",
    "spatie/laravel-ignition": "^1.0",
    "thedoctor0/laravel-mailjet-driver": "1.0.4",
    "twilio/sdk": "^6.34",
    "vlucas/phpdotenv": "^5.2",
    "voku/portable-utf8": "^6.0",
    "voku/simple_html_dom": "^4.7",
    "web-token/jwt-easy": "^2.2",
    "web-token/jwt-key-mgmt": "^2.2",
    "web-token/jwt-signature": "^2.2",
    "web-token/jwt-signature-algorithm-rsa": "^2.2",
    "zircote/swagger-php": "^3.0"
  },
  "require-dev": {
	"barryvdh/laravel-ide-helper": "^2.9",
	"fakerphp/faker": "^1.13",
	"kitloong/laravel-migrations-generator": "^5.0",
	"mockery/mockery": "^1.3.1",
	"nunomaduro/collision": "^6.1",
	"phpunit/phpunit": "^9.5"
  },
  "config": {
	"optimize-autoloader": true,
	"preferred-install": "dist",
	"sort-packages": true
  },
  "extra": {
	"laravel": {
	  "dont-discover": []
	}
  },
  "autoload": {
	"psr-4": {
	  "App\\": "app/",
	  "Database\\Factories\\": "database/factories/",
	  "Database\\Seeders\\": "database/seeds"
	},
	"classmap": [
	  "database/seeds"
	],
	"files": [
	  "app/helpers.php"
	]
  },
  "autoload-dev": {
	"psr-4": {
	  "Tests\\": "tests/"
	}
  },
  "minimum-stability": "dev",
  "prefer-stable": true,
  "scripts": {
	"post-autoload-dump": [
	  "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
	  "@php artisan package:discover --ansi"
	],
	"post-root-package-install": [
	  "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
	],
	"post-create-project-cmd": [
	  "@php artisan key:generate --ansi"
	]
  }
}
```

### PR DESCRIPTION
**Pull request by Messhias**
- Added config option to allow ignition usage in localhost.
- Update .gitignore file.

Closes #81.

### CODE REVIEW

**Comment by Messhias** [comment]
@AlexVanderbist

**Comment by freekmurze** [comment]
It seems like this change will make solutions not runnable locally by default. 

Can you explain why this change is needed?

**Comment by Messhias** [comment]
> It seems like this change will make solutions not runnable locally by default.
> 
> Can you explain why this change is needed?

Previously wasn't not even working on local usage.

Because this should be decided by the developer and if you see it previously we cannot make it run local accordingly with #81.

**Comment by AlexVanderbist** [comment]
Hi there, thanks for the PR! Code looks good but to avoid having two very similar environment variables (`IGNITION_ALLOW_LOCAL_USAGE` and `IGNITION_ENABLE_RUNNABLE_SOLUTIONS`) we decided to take it in a slightly different direction. See #111 for more information.

**Pull request closed without merging**
