### PR TITLE
fix finding original file using compiled filepath

### PR DESCRIPTION
**Pull request by jcmcclorey**
Fixes issue with Blade template not resolving #104

### CODE REVIEW

**Comment by freekmurze** [comment]
Could you add a test for this?

**Comment by SocolaDaiCa** [comment]
use realpath instead

image

**Comment by fahrim** [comment]
I updated to version 1.6.4 in my current project. but I still see the error in the cached view.

As a note: I cleared the cache, restarted the server.

**Comment by SocolaDaiCa** [comment]
@fahrim try `php artisan view:clear`

**Pull request closed without merging**
