### PR TITLE
The possibility to specify a path to the settings file

### PR DESCRIPTION
**Pull request by kudashevs**
Hello,

This is a draft of the spatie/ignition#57 which adds the possibility to specify a file where the settings will be saved.

### CODE REVIEW

**Comment by kudashevs** [comment]
@AlexVanderbist hello again,

Here is a small update. I planned to use a mock of `ConfigManager` more like a stub (just return something without any expectations check). However, in this case, it seems more reasonable to check the expectations too. What do you think about it in this case? Would you prefer stubbing or mocking in this situation?

Btw, what are the next steps? Should I wait for a review? Or should I change the `composer.json` ignition dependency to a normal one? I mean I have never been in the situation where the tests won't pass (`UpdateConfigControllerTest.php` won't pass) unless a new package version (the new `spatie\ignition` with the `ConfigManager` class) will be released.

**Comment by AlexVanderbist** [comment]
hi again @kudashevs, I had already tagged your changes to `spatie/ignition` so I've updated the composer.json to use that new version in this PR. Looks like tests are passing too!

Regarding the mock vs stub matter: I think it's fine the way you did it now. The composer dependency is locked to only use the updated Ignition version that already includes tests for everything in the `ConfigManager`. I feel like it's definitely good enough to just check the mock's methods are being called :)

Next steps: looks good to merge for me! Unless you still want to add something, you can remove the DRAFT from title and I'll merge and tag it! Thanks again for the PRs :D

**Comment by drekinov** [comment]
i hope that is processed soon as we figure out that there is hardcoded paths in the package because of more restrictive `open_base` directives we implemented.

**Comment by kudashevs** [comment]
> Regarding the mock vs stub matter: I think it's fine the way you did it now. The composer dependency is locked to only use the updated Ignition version that already includes tests for everything in the `ConfigManager`. I feel like it's definitely good enough to just check the mock's methods are being called :)
> 

Thank you for your detailed answer.

> Next steps: looks good to merge for me! Unless you still want to add something, you can remove the DRAFT from title and I'll merge and tag it! Thanks again for the PRs :D

I'm not sure about additional changes for now. Let's give it a go and see a feedback.

**Comment by kudashevs** [comment]
> i hope that is processed soon as we figure out that there is hardcoded paths in the package because of more restrictive `open_basedir` directives we implemented.

Could you please give a little bit more information? What hardcoded paths are you referring to? Are you referring to [this PR](https://github.com/spatie/ignition/issues/22)?

**Comment by drekinov** [comment]
> > i hope that is processed soon as we figure out that there is hardcoded paths in the package because of more restrictive `open_basedir` directives we implemented.
> 
> Could you please give a little bit more information? What hardcoded paths are you referring to? Are you referring to [this PR](https://github.com/spatie/ignition/issues/22)?

Ah maybe yes.
issue started with spatie/ignition#90 (just pushed).
however we find a smart way to have whatever path we want without any package changes.

```php
# boostrap/app.php
$app->singleton(\Spatie\Ignition\Contracts\ConfigManager::class, function() {
return new \Spatie\Ignition\Config\FileConfigManager(_WHATEVER_CUSTOM_PATH_YOU_WANT_);
});
```

**Comment by AlexVanderbist** [comment]
hey @drekinov, @kudashevs,

>we were not able to use service providers because Ignition one was loaded before anything in config/app.php

That's a good point. Maybe we should add a config value to this package to specify the `config_manager_class`? It can be set to `\Spatie\Ignition\Config\FileConfigManager::class` by default. That way anyone that wants to overwrite this can simple update the config file? What do you think?

**Comment by kudashevs** [comment]
> That's a good point. Maybe we should add a config value to this package to specify the `config_manager_class`? It can be set to `\Spatie\Ignition\Config\FileConfigManager::class` by default. That way anyone that wants to overwrite this can simple update the config file? What do you think?

@AlexVanderbist I barely understand the problem with service providers and why it is impossible to use them before Ignition (as Ignition is initialized through the service provider). It seems like the origin of the problem is in the initialization process (the old version of `spatie/laravel-ignition` doesn't take into account the new `FileConfigManager` class from `spatie/ignition`). And this PR (with the updated `registerIgnition` method) should resolve it. So, there won't be the necessity to update the `bootstrap/app.php` file. If I'm mistaken could you please correct me?

However, I totally agree with this `config_manager_class` option and it perfectly suits the idea to separate the realizations which we discussed before (to separate FileConfigManager and EnvironmentConfigManager).

**Comment by kudashevs** [comment]
> > Next steps: looks good to merge for me! Unless you still want to add something, you can remove the DRAFT from title and I'll merge and tag it! Thanks again for the PRs :D
> 
> I'm not sure about additional changes for now. Let's give it a go and see a feedback.

@AlexVanderbist Excuse me, do you have any plans to merge it? I removed the DRAFT from the title 5 days ago.

**Comment by freekmurze** [comment]
Please have some patience. We'll take a look when we have some time.

**Comment by kudashevs** [comment]
> Please have some patience. 

@freekmurze hello, 

This was just the question to clarify the situation, without any impatience or so. There is a problem here, that this PR is dependent to [the PR](https://github.com/spatie/ignition/pull/57) and it was assumed that both of these PRs would be merged almost simultaneously (this moment was mentioned). So, issues (like the issue above) will have happened until this PR is not merged.

> We'll take a look when we have some time.
This PR was reviewed 5 days ago and the only request at that time was to change the title. I changed the title almost immediately because I feel the responsibility for this PR and want everything work well. So, this time shift looks stange to me. If it needs more time you guys should have said something about it.

**Comment by AlexVanderbist** [comment]
Hey @kudashevs, sorry about the delay. Let's get this merged :)

**Pull request merged**
